name: source to image custom action
description: docker custom action
inputs:
   registry:
     type: string
     required: true
   username:
     type: string
     required: true
   password:
     type: string
     required: true
   image-name:
     type: string
     required: true
   tag:
     type: string
     default: latest
     required: false
outputs:
  image_name:
    description: full image name with sha
  image_digest:
    description: docker image digest
  push_status:
    description: push status
runs:
  using: 'docker'
  image: 'Dockerfile.react'
  args:
    - -v
    - /var/run/docker.sock:/var/run/docker.sock