FROM nginx:alpine

RUN apk add --no-cache docker-cli bash

RUN rm -rf /usr/share/nginx/html/*

COPY ./frontend/dist /usr/share/nginx/html

RUN echo 'server { \
    listen 80; \
    location / { \
        root /usr/share/nginx/html; \
        index index.html index.htm; \
        try_files $uri $uri/ /index.html; \
    } \
}' > /etc/nginx/conf.d/default.conf

EXPOSE 80

ENTRYPOINT ["/bin/bash", ".github/actions/react-docker-s2i/entrypoint.sh"]


